
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package imageneditor.analisis;

import java_cup.runtime.*;
import imageneditor.DefaultValue;
import imageneditor.objectsManager.pintarManager;
import imageneditor.exceptions.InputsVaciosException;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class paint extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public paint() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public paint(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public paint(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\030\000\002\002\004\000\002\002\005\000\002\002" +
    "\003\000\002\003\006\000\002\005\005\000\002\006\005" +
    "\000\002\006\003\000\002\015\003\000\002\015\005\000" +
    "\002\007\005\000\002\007\005\000\002\007\003\000\002" +
    "\007\003\000\002\004\011\000\002\010\004\000\002\010" +
    "\004\000\002\010\003\000\002\010\003\000\002\014\006" +
    "\000\002\013\013\000\002\011\003\000\002\011\005\000" +
    "\002\012\003\000\002\012\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\070\000\006\005\005\044\006\001\002\000\004\002" +
    "\uffff\001\002\000\004\035\057\001\002\000\004\031\014" +
    "\001\002\000\004\044\006\001\002\000\004\002\011\001" +
    "\002\000\004\002\001\001\002\000\006\005\005\044\006" +
    "\001\002\000\004\002\000\001\002\000\004\042\015\001" +
    "\002\000\004\032\016\001\002\000\004\035\017\001\002" +
    "\000\006\004\020\042\024\001\002\000\004\031\041\001" +
    "\002\000\004\036\040\001\002\000\010\004\020\036\ufff0" +
    "\042\024\001\002\000\010\004\020\036\ufff1\042\024\001" +
    "\002\000\004\022\025\001\002\000\006\042\027\045\030" +
    "\001\002\000\010\023\032\024\031\030\033\001\002\000" +
    "\016\023\ufff6\024\ufff6\025\ufff6\026\ufff6\030\ufff6\032\ufff6" +
    "\001\002\000\016\023\ufff5\024\ufff5\025\ufff5\026\ufff5\030" +
    "\ufff5\032\ufff5\001\002\000\006\042\027\045\030\001\002" +
    "\000\006\042\027\045\030\001\002\000\010\004\uffef\036" +
    "\uffef\042\uffef\001\002\000\016\023\ufff7\024\ufff7\025\ufff7" +
    "\026\ufff7\030\ufff7\032\ufff7\001\002\000\016\023\ufff8\024" +
    "\ufff8\025\ufff8\026\ufff8\030\ufff8\032\ufff8\001\002\000\004" +
    "\036\ufff3\001\002\000\004\036\ufff2\001\002\000\010\002" +
    "\ufff4\005\ufff4\044\ufff4\001\002\000\004\042\042\001\002" +
    "\000\004\025\043\001\002\000\006\042\027\045\030\001" +
    "\002\000\004\025\050\001\002\000\012\023\032\024\031" +
    "\025\uffed\026\046\001\002\000\006\042\027\045\030\001" +
    "\002\000\010\023\032\024\031\025\uffec\001\002\000\006" +
    "\042\027\045\030\001\002\000\004\032\055\001\002\000" +
    "\012\023\032\024\031\026\053\032\uffeb\001\002\000\006" +
    "\042\027\045\030\001\002\000\010\023\032\024\031\032" +
    "\uffea\001\002\000\004\030\056\001\002\000\010\004\uffee" +
    "\036\uffee\042\uffee\001\002\000\004\043\061\001\002\000" +
    "\004\036\072\001\002\000\004\042\064\001\002\000\004" +
    "\030\071\001\002\000\006\025\067\030\ufffb\001\002\000" +
    "\010\022\065\025\ufffa\030\ufffa\001\002\000\006\042\027" +
    "\045\030\001\002\000\012\023\032\024\031\025\ufff9\030" +
    "\ufff9\001\002\000\004\042\064\001\002\000\004\030\ufffc" +
    "\001\002\000\004\036\ufffd\001\002\000\004\044\ufffe\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\070\000\010\002\007\003\006\004\003\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\011\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\002\012\003\006\004\003\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\010\020\013\021\014\022\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\010\036\013\021\014\022\001" +
    "\001\000\010\010\035\013\021\014\022\001\001\000\002" +
    "\001\001\000\004\007\025\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\034\001\001" +
    "\000\004\007\033\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\007\044\011\043\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\046\001\001\000\002\001\001\000" +
    "\006\007\051\012\050\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\053\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\057\001\001" +
    "\000\002\001\001\000\006\006\061\015\062\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\065\001\001\000\002\001\001\000\006\006\067\015" +
    "\062\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$paint$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$paint$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$paint$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




	pintarManager newPaintM;
	int posX =DefaultValue.noInicioDimension;
	int posXint = DefaultValue.noInicioDimension;
	int posY =DefaultValue.noInicioDimension;
	int posYint = DefaultValue.noInicioDimension;

	public paint(Lexer lex, pintarManager pntIn){
		super(lex);
		this.newPaintM = pntIn;
	}

	private void setPosX(int xPnt) throws InputsVaciosException {
		if (posX == DefaultValue.noInicioDimension) {
			posX = xPnt;
		} else {
			throw new InputsVaciosException("Posicion X " + xPnt + " can't set");
		}
	}

	private void setPosXint(int xPnt) throws InputsVaciosException {
		if (posXint == DefaultValue.noInicioDimension) {
			posXint = xPnt;
		} else {
			throw new InputsVaciosException("Posicion X " + xPnt + " can't set");
		}
	}

	private void setPosY(int yPnt) throws InputsVaciosException {
		if (posY == DefaultValue.noInicioDimension) {
			posY = yPnt;
		} else {
			throw new InputsVaciosException("Posicion X " + yPnt + " can't set");
		}
	}

	private void setPosYint(int yPnt) throws InputsVaciosException {
		if (posYint == DefaultValue.noInicioDimension) {
			posYint = yPnt;
		} else {
			throw new InputsVaciosException("Posicion X " + yPnt + " can't set");
		}
	}

	private String valorSuma(String val1, String val2){
		return String.valueOf(Integer.parseInt(val1) + Integer.parseInt(val2));
	}

	private String valorResta(String val1, String val2){
		return String.valueOf(Integer.parseInt(val1) - Integer.parseInt(val2));
	}

	public void syntax_error(Symbol cur_token) {
		String message = "Estructura invalida en posición " + cur_token.right
			 + ", token: " + cur_token.value;
		System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<");	 
		System.out.println(message);
		System.out.println("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
	}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$paint$actions {
  private final paint parser;

  /** Constructor */
  CUP$paint$actions(paint parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$paint$do_action_part00000000(
    int                        CUP$paint$act_num,
    java_cup.runtime.lr_parser CUP$paint$parser,
    java.util.Stack            CUP$paint$stack,
    int                        CUP$paint$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$paint$result;

      /* select the action based on the action number */
      switch (CUP$paint$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= PAINT EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-1)).value;
		RESULT = start_val;
              CUP$paint$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-1)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$paint$parser.done_parsing();
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // PAINT ::= VARIABLES INSTRUCCIONS PAINT 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("PAINT",0, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PAINT ::= INSTRUCCIONS 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("PAINT",0, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // VARIABLES ::= Vars LlaveAbierta SET_VARIABLE LlaveCerrada 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("VARIABLES",1, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-3)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SET_VARIABLE ::= NewVar DATA PuntoYComa 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("SET_VARIABLE",3, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // DATA ::= NEW_VAR Coma DATA 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("DATA",4, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // DATA ::= NEW_VAR 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("DATA",4, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NEW_VAR ::= Identificador 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;
		 newPaintM.addVariable(e); 
              CUP$paint$result = parser.getSymbolFactory().newSymbol("NEW_VAR",11, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // NEW_VAR ::= Identificador Igual MATH_OP 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;
		 newPaintM.addVariable(e1, Integer.parseInt(e2)); 
              CUP$paint$result = parser.getSymbolFactory().newSymbol("NEW_VAR",11, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // MATH_OP ::= MATH_OP Mas MATH_OP 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;
		 RESULT = valorSuma(e1, e2); 
              CUP$paint$result = parser.getSymbolFactory().newSymbol("MATH_OP",5, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // MATH_OP ::= MATH_OP Menos MATH_OP 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;
		 RESULT = valorResta(e1, e2); 
              CUP$paint$result = parser.getSymbolFactory().newSymbol("MATH_OP",5, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // MATH_OP ::= Identificador 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;
		 RESULT = String.valueOf(newPaintM.varValue(e)); 
              CUP$paint$result = parser.getSymbolFactory().newSymbol("MATH_OP",5, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // MATH_OP ::= Entero 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;
		 RESULT = e; 
              CUP$paint$result = parser.getSymbolFactory().newSymbol("MATH_OP",5, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // INSTRUCCIONS ::= Instrucciones ParAbierto Identificador ParCerrado LlaveAbierta INT_BODY LlaveCerrada 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONS",2, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-6)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // INT_BODY ::= VAR_VALUE INT_BODY 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("INT_BODY",6, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-1)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // INT_BODY ::= PAINT_COM INT_BODY 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("INT_BODY",6, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-1)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // INT_BODY ::= VAR_VALUE 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("INT_BODY",6, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // INT_BODY ::= PAINT_COM 
            {
              String RESULT =null;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("INT_BODY",6, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // VAR_VALUE ::= Identificador Igual MATH_OP PuntoYComa 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-3)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-1)).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-1)).value;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("VAR_VALUE",10, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-3)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // PAINT_COM ::= Pintar ParAbierto Identificador Coma POS_X Coma POS_Y ParCerrado PuntoYComa 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-6)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-6)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-6)).value;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("PAINT_COM",9, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-8)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // POS_X ::= MATH_OP 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("POS_X",7, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // POS_X ::= MATH_OP Intervalo MATH_OP 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("POS_X",7, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // POS_Y ::= MATH_OP 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("POS_Y",8, ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // POS_Y ::= MATH_OP Intervalo MATH_OP 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.elementAt(CUP$paint$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$paint$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$paint$stack.peek()).value;

              CUP$paint$result = parser.getSymbolFactory().newSymbol("POS_Y",8, ((java_cup.runtime.Symbol)CUP$paint$stack.elementAt(CUP$paint$top-2)), ((java_cup.runtime.Symbol)CUP$paint$stack.peek()), RESULT);
            }
          return CUP$paint$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$paint$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$paint$do_action(
    int                        CUP$paint$act_num,
    java_cup.runtime.lr_parser CUP$paint$parser,
    java.util.Stack            CUP$paint$stack,
    int                        CUP$paint$top)
    throws java.lang.Exception
    {
              return CUP$paint$do_action_part00000000(
                               CUP$paint$act_num,
                               CUP$paint$parser,
                               CUP$paint$stack,
                               CUP$paint$top);
    }
}

}
