
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package imageneditor.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Nombre = 14;
  public static final int Entero = 31;
  public static final int Coma = 19;
  public static final int ParAbierto = 23;
  public static final int Tamanio = 13;
  public static final int Colores = 4;
  public static final int Dimension = 5;
  public static final int Menos = 17;
  public static final int HexaCode = 30;
  public static final int Mas = 18;
  public static final int Lienzos = 15;
  public static final int PuntoYComa = 22;
  public static final int Blue = 9;
  public static final int CorAbierto = 25;
  public static final int Cuadro = 6;
  public static final int Pintar = 2;
  public static final int Hex = 7;
  public static final int LlaveCerrada = 28;
  public static final int Cadena = 32;
  public static final int Red = 8;
  public static final int EOF = 0;
  public static final int DosPuntos = 21;
  public static final int error = 1;
  public static final int Green = 10;
  public static final int Comment = 29;
  public static final int Tipo = 11;
  public static final int Vars = 3;
  public static final int NewVar = 34;
  public static final int ParCerrado = 24;
  public static final int Intervalo = 20;
  public static final int Instrucciones = 35;
  public static final int Identificador = 33;
  public static final int LlaveAbierta = 27;
  public static final int Fondo = 12;
  public static final int Igual = 16;
  public static final int CorCerrado = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Pintar",
  "Vars",
  "Colores",
  "Dimension",
  "Cuadro",
  "Hex",
  "Red",
  "Blue",
  "Green",
  "Tipo",
  "Fondo",
  "Tamanio",
  "Nombre",
  "Lienzos",
  "Igual",
  "Menos",
  "Mas",
  "Coma",
  "Intervalo",
  "DosPuntos",
  "PuntoYComa",
  "ParAbierto",
  "ParCerrado",
  "CorAbierto",
  "CorCerrado",
  "LlaveAbierta",
  "LlaveCerrada",
  "Comment",
  "HexaCode",
  "Entero",
  "Cadena",
  "Identificador",
  "NewVar",
  "Instrucciones"
  };
}

